"""SQLAlchemy ORM base: DeclarativeBase, mixins, and UUID helper.

All ORM models inherit from ``Base`` (generated by ``DeclarativeBase``).
Common column patterns are encapsulated in mixins rather than repeated
across model files.

``TimestampMixin``
    Adds ``created_at`` and ``updated_at`` columns to any model.
    ``updated_at`` is automatically refreshed on every UPDATE via
    ``onupdate=func.now()``.  Both columns are timezone-aware
    (``TIMESTAMP WITH TIME ZONE``) to avoid silent TZ confusion.

``UUIDPrimaryKeyMixin``
    Adds a UUID primary-key column with a server-side default.  Using
    ``uuid_generate_v4()`` (PostgreSQL) or ``gen_random_uuid()`` ensures
    the DB generates collision-free IDs even if the application server
    restarts between the key generation and the INSERT.

    For SQLite (development), we fall back to ``uuid4()`` via a Python
    ``default`` callable, because SQLite has no native UUID function.

SQLAlchemy 2.x typed mapped columns
    We use ``Mapped[T]`` and ``mapped_column()`` throughout.  This provides
    full mypy type inference for model attributes without a plugin.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Project-wide SQLAlchemy declarative base.

    Import and inherit this in every ORM model file.  Alembic's
    ``env.py`` imports ``Base.metadata`` to detect all mapped tables
    for autogenerate.
    """

    pass


class TimestampMixin:
    """Adds ``created_at`` and ``updated_at`` to any ORM model.

    ``created_at``: Set once on INSERT; never changed.
    ``updated_at``: Set on INSERT and refreshed automatically on every UPDATE.

    Both columns are ``NOT NULL``, UTC, and timezone-aware so that
    cross-region deployments produce consistent timestamps.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        doc="Timestamp of record creation (UTC, set once on INSERT).",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        doc="Timestamp of last update (UTC, auto-refreshed on every UPDATE).",
    )


class UUIDPrimaryKeyMixin:
    """Adds a UUID primary-key column with a Python-side default.

    Using a Python-side default (``default=uuid.uuid4``) rather than a
    server-side default keeps the ID available *before* the INSERT is
    flushed.  This is important for building relationships between objects
    in the same unit of work before committing.

    The ID is stored as a native UUID type where the database supports it
    (PostgreSQL), or as a 36-character string on SQLite.  SQLAlchemy's
    ``Uuid`` type handles the conversion transparently.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
        doc="UUID4 primary key, generated server-side before INSERT.",
    )
